# Generated by Django 4.0.4 on 2022-05-09 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('prof_name', models.CharField(max_length=200)),
                ('memo', models.CharField(max_length=200)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='subjectApp.major')),
            ],
        ),
    ]
